#+类型: 2203
#+主页: [[归档202203]]

* 周一 [[2022_03_14]] [[Mar 14th, 2022]]
** #今日鸡汤 #周记 #疫情

张宏文，划重点：1. 消除恐惧是我们必须走出的第一步；2. 争论毫无意义。事儿得一步一步做。目前完全放开，不可能也不现实；3. 奥密克戎这波是倒春寒！谢谢张医生，非常清晰！

** #今日文章 #周记

《学生和玉佛》

一月二十八日《申报》号外载二十七日北平专电曰：故宫古
物即起运，北宁平汉两路已奉令备车，团城白玉佛亦将南运。

二十九日号外又载二十八日中央社电传教育部电平各大学，
略曰：“据各报载榆关告紧之际，北平各大学中颇有逃考及提前
放假等情，均经调查确实。查大学生为国民中坚份子，讵容妄自
惊扰，败坏校规，学校当局迄无呈报，迹近宽纵，亦属非是。仰
该校等迅将学生逃考及提前放假情形，详报核办，并将下学期上
课日期，并报为要。

三十日，“堕落文人”周动轩先生见之，有诗叹曰：

寂寞空城在，仓皇古董迁，

头儿夸大口，面子靠中坚。

惊扰讵云妄？奔逃只自怜：

所嗟非玉佛，不值一文钱。


* 周二 [[2022_03_15]] [[Mar 15th, 2022]]
** #今日鸡汤 #周记

成年人有一点很重要需要注意：直接拒绝，比有条件拒绝要重要。 #箴言

** #今日文章 #周记

保尔·艾吕雅的《宵禁》

门口有人把守着你说怎么办

我们被人禁闭着你说怎么办

街上交通断绝了你说怎么办

城市被人控制着你说怎么办

全城居民在挨饿你说怎么办

我们手里没武器你说怎么办

黑夜已经来到了你说怎么办

我们因此相爱了你说怎么办


* 周三 [[2022_03_16]] [[Mar 16th, 2022]]
** #今日鸡汤 #周记

死亡不是消失，遗忘才是，有位老友，我经常点进他朋友圈看，只是没再更新。 #人生

** #今日文章 #周记

《善其事必先休息好》

长时间耗在一个问题上，身体和大脑都会疲惫。当心态失衡时，解决问题的能力也会直线下降。我经常会陷入一种急迫解决问题的困境，直到身体完全扛不住才放弃。这其实是一种低效的方式，情绪会在这个过程中逐渐压制理智，让人很难全面的思考问题。

与自己平和相处，接纳自己的不足，休息好重新出发才能走的更长远。所以当遇到自己很难解决的问题时，试着先确保身体状态是正常的，如果身体很疲惫，先休息而不是直接攻克难题。


* 周四 [[2022_03_17]] [[Mar 17th, 2022]]
** #今日鸡汤 #周记

有些人：你好好和他说话，他爱答不理；臭骂他一顿，反而老实了。这是慕强心理在作怪，不适合所有人，但适合一部分人。你总是做事碰壁，可以试一下这个方法。

** #今日文章 #周记

《人日鸡汤：要享受苦难》 

在同一辆列车上，有人感染有人安全，这是机体免疫力；

同样的隔离，有人一年吃喝不愁，有人一周就拮据，这是财务免疫力；

同样呆在家里，有人读书、学习、锻炼，空中课堂，努力提升，
有人睡觉、电视、打游戏。混混沌沌过一天，这是价值免疫力；

一样的灾难，有人阳光向上勇往直前，有人怨天尤人、仇视社会，这是心理免疫力；

这场灾难，是一个大浪淘沙的过程，对所有人的体质、认知、阅历、人性、良知、勇气、思想、灵魂、价值观……。

是一次赤裸裸的筛选。所以，战胜意外与不幸，最重要的是提升所有的免疫力。

* 周五 [[2022_03_18]] [[Mar 18th, 2022]]
** #今日鸡汤 #周记

知识来源于生活，也是驾驭生活的能力，所以，学习跟生活中的很多道理是互通的，都是一样一样的。 #读书与思考

** #今日文章 #周记

《家族的重要性》

曾经有人说过一句非常扎心的话，说平民子弟，真正明白社会真相，普遍在 40 岁。但已经进不了圈子，上不了盘桌。富贵子弟，25 岁已经洞若观火，杀伐决断了。

仔细回头想想，不得不承认，现实很多时候还真是这么回事。人生最大的浪费，其实不是金钱的浪费，而是自己努力奋斗了半生，发现自己拼命往前的路走错了，方向走偏了。再回头，为时已晚。

普通人走弯路，最根本的还是因为自己认知局限，包括身边能影响和帮助自己的人认知也存在局限。


* 周六 [[2022_03_19]] [[Mar 19th, 2022]]
** #今日鸡汤 #周记

丰县这件事的巨大意义，是让有女孩子的家长明白：如果十几亿上百亿的点击量都突破不了一个村子，都救不了她，你掂量一下你的财力和资源，有多大的抗风险能力。为了你自己后代负责为了你自己不悲伤欲绝、家破人亡：你是生？还是不生？你是留？还是不留？ #八孩妈

** #今日文章 #周记

《无题》 #疫情

内地这一轮爆发到现在，实践加上一些半遮半掩的信息传播，显然是大部分人都知道死不了什么人了。致病性弱了致死率低了，这本来是好事，但目前这个机制下面是没有好事的，好事一定会变成坏事，而且是更扭曲的坏事。死不了人反倒给了掌权者们一个更加宽松的环境，任由他们随便怎么胡搞。深圳搞核酸检测搞得跟庙会似的，比庙会还挤，这是怕感染的架势吗？大厂不让员工回家办公，每天下班排个把小时的队测核酸就为了第二天进办公室，街头巷尾人头涌涌，这是防病毒的姿势吗？后来要封闭了，把员工封在办公楼里、赶到外边的帐篷里让人带电脑接着上班，快递员东一堆西一堆睡在大街上，要是 covid19 还有 20 年初的致死率，他们敢吗？江苏徐州，进别的地方不看核酸，进丰县董集村就查核酸了，这说明什么，说明村一级的流氓，也明白现在所谓查核酸实际上是个什么东西。

积累到现在，种种扭曲，已经扭不过来了。早打上有用的疫苗也不至于爆发，问题打的是没用的疫苗；感染了其实也还好，但前期渲染的恐怖深入人心，放开了又怕轻症也跑医院造成挤兑；直到现在为了灌输被害妄想还在严查快递藏毒，但同时又在大规模封锁，一个区一个村的禁足，你不让快递上路想干嘛？饿死人？

下一步怎么办，抗原自测也试点了，辉瑞的药也批了，最重要的标志中医也出来推销针灸疗法了，都说明决策者心里有数，知道我们即将迎来抗疫的春天。只不过政策有它的尊严，特师说什么：猫吃塑料袋，你给猫指出，猫把你杀了。猫不开口，就得接着清零，接着就地免职，接着全民检测，人都折腾麻了，只有万孚生物董秘这号人物在朋友圈喜大普奔。你得等猫自己说，但你又得求着猫说，跟禅让似的，三推四请，最后猫开口赐给广大人民群众一个稍微正常一点的生活，从胜利走向胜利!真他妈恶心透顶。


* 周日 [[2022_03_20]] [[Mar 20th, 2022]]
** #今日鸡汤 #周记

7

** #今日文章 #周记

7

