* [[2022_02_21]] [[Feb 21st, 2022]]
** #今日鸡汤 #周记

徐州事件彻底击穿了人们的安全和道德底线：那些原本以为岁月静好的“岁静”者，也终于认清了自己和那一条铁链的距离。

** #今日文章 #周记

《清醒点，请别再“郁郁不得志”》

你每天睡到自然醒，醒了刷抖音玩游戏，等你饿的时候起床，发现已经中午了，吃个午饭继续睡觉，下午醒了继续玩，然后吃晚饭，一天就这样过去了。

你外貌不出众，能力不出众，家庭不出众，却心比天高，明明自己狗屁不是，却谁都看不上，每天刷着抖音羡慕别人的生活，羡慕着别人的爱情，幻想自己也能拥有一切。

然后你看了看镜子里的自己，普普通通的外貌，普普通通的身材，三天没洗的油头，乱七八糟的穿搭。

你没有上进心，却又幻想自己的另一半足够优秀，带出去能让别人羡慕自己，给自己涨面子，那 Ta 又凭什么看得上你呢？

清醒点，请别再“郁郁不得志”。


* [[2022_02_22]] [[Feb 22nd, 2022]]
** #今日鸡汤 #周记

根据相关法律法规和政策，该内容已无法被公开查看。

** #今日文章 #周记

《人与时》

一人说，将来胜过现在。

一人说，现在远不及从前。

一人说，什么?
时道，你们都侮辱我的现在。

从前好的，自己回去。
将来好的，跟我前去。

这说什么的，
我不和你说什么。

【注释】本篇最初发表于一九一八年七月十五日《新青年》第五卷第一号，署名唐俟。


* [[2022_02_23]] [[Feb 23rd, 2022]]
** #今日鸡汤 #周记

妈妈带着爸爸去德国治疗肺癌，我傻傻信了他们是去出差顺便旅游，最后妈妈带着爸爸尸体回来的，连爸爸最后一面都没有见到。

** #今日文章 #周记 #八孩妈

《小花梅（当代民谣）》

作者：大风如刀

小花梅，小花梅，
身世飘零你是谁？
千家万户乖乖女，
一别爹娘唤不归。
唤不归，小花梅，
骨肉亲情梦相随。
可怜天下父母心，
多少血泪化成灰。

小花梅，小花梅，
飘来飘去你是谁？
燕山雪花大如席，
王师不讨盗花贼。
盗花贼手段黑，
官家助力草上飞。
盲山多少拴狗链。
拴的都是小花梅。

小花梅，小花梅，
命如蝼蚁你是谁？
莫说世界不要俺，
天道不存万户悲。
万户悲，小花梅，
怒指长安绣成堆。
歌舞升平豪门宴，
笙管排萧夜夜吹。

小花梅，小花梅，
声声血泪声声悲。
干呼万唤人神愤，
怒海狂潮誓灭贼！
誓灭贼，胡不归？
管他式微不式微。
但凭苍生十四亿，
不信天谴不轮回！

20220211


* [[2022_02_24]] [[Feb 24th, 2022]]
** #今日鸡汤 #周记

这件事将来一定会上史书的，历史如刀，看谁能逃。 

** #今日文章 #周记

《正能量》

你说我经常在群里发一些负面的内容，搞的你不悦。其实我也有很多正面的讯息，也就是你说的正能量的事情：
1. 我昨晚娃都睡了，我起来给 kindle 换了电池，有可以再战 2 年了；
2. 我朋友的弟弟裸考过六级、昨天考研成绩初试出来 414 分；
3. 我朋友自己写了个语言，我试了了，很不错；
4. 昨天我搞定了一个困扰有小半年的软件安装问题：先升级 Debian 系统，再重新安装；
5. 我朋友下个月生二胎，儿女双全；
……

我想说的是：正能量其实很多，但是我们更应该面对负面，保持乐观的心态，积极的去生活。


* [[2022_02_25]] [[Feb 25th, 2022]]
** #今日鸡汤 #周记

不管是知识、认知、人脉、财力……，不管好赖，这些东西一个家族本身都在传承，人不是完全从零开始的

#今日文章 #周记 #八孩妈

《拐卖的婚姻不应合法》

最大的逻辑矛盾是什么？是办结婚证的过程已经确认违法，相关人员也已追责了，婚姻却仍然被认定为真实有效，买家仍然被认定为“丈夫”，按照家庭成员虐待罪而不是绑架、伤害罪追究。

如果说早年司法实践中有不得已的妥协，那么时到今日，“拐卖婚无效”这一基本原则应成为共识。否则，就是变相承认买卖婚，把拐卖这一严重犯罪偷换成“家庭事务”，买卖同罪也将成为空谈。

此外拐卖婚姻并不适用“事实婚姻”。事实婚姻是指男女双方在主观上具有永久生活的目的，在客观上具有未经结婚登记机关登记，未领取结婚证即以夫妻名义同居生活的事实。且 1994 年后，我国已不承认事实婚姻。