#+类型: 2203
#+主页: [[归档202203]]

* 周一 [[2022_03_07]] [[Mar 7th, 2022]]
** #今日鸡汤 #周记

人的一生，其实就是时间和注意力分配的过程，你所专注的一切，反过来定义了你是谁，因此要格外珍惜你的注意力，认真选择你的情绪和思想所聚焦的对象。
如果你只是不停被喧嚣带走注意力，或总是纠结于错误的事与人，迟早你会被外界塑造或污染，成为你不想成为的人，白白浪费掉你仅有一次的生命。

** #今日文章 #周记

《战争》

战争就是某个大人物打着国家的旗号，驱赶底层老百姓上战场血拼。一个农民的儿子奔赴万里去杀死素不相识的另一个农民的儿子。最后死去的农民儿子得到的只是被吹得无比神圣的一块铜制的小牌牌和一面旗帜。父母失去了儿子，妻子失去丈夫，儿女失去了父亲。而无数农民儿子用命换来的却是那个大人物坐稳的宝座和一生的富贵。


* 周二 [[2022_03_08]] [[Mar 8th, 2022]]
** #今日鸡汤 #周记

中国人的神逻辑一：1. 你饭都没吃饱还关心这个干嘛？2. 你都吃饱饭了还关心这个干嘛？
中国人的神逻辑二：1. 上面的政策是好的，都是下面的人把经念歪了；2. 下面的人也没办法，都是上边要求的。


** #今日文章 #周记

《二零二二年三月六日》

在这儿你不能愤怒，否则你会时时处于愤怒中，而愤怒无济于事，除了微弱地证明你的心还没有变成铁、变成水泥、变成塑料，或者随便什么。

那么你该怎么办没错，她不是你，早晨醒来你的脖子上没有一根锁住的铁链，昨晚你也不在逃难的人群中，你的天空没有炸弹在飞，你窗前的花像从前一样迎接春日。

但此刻你感到快乐是一种羞耻，平静地生活是一种羞耻。

20220306


* 周三 [[2022_03_09]] [[Mar 9th, 2022]]
** #今日鸡汤 #周记

三

** #今日文章 #周记

三


* 周四 [[2022_03_10]] [[Mar 10th, 2022]]
** #今日鸡汤 #周记

四

** #今日文章 #周记

四


* 周五 [[2022_03_11]] [[Mar 11th, 2022]]
** #今日鸡汤 #周记

五

** #今日文章 #周记

五


* 周六 [[2022_03_12]] [[Mar 12th, 2022]]
** #今日鸡汤 #周记

六

** #今日文章 #周记

六


* 周日 [[2022_03_13]] [[Mar 13th, 2022]]
** #今日鸡汤 #周记

日

** #今日文章 #周记

日

