#+类型: 2203
#+主页: [[归档202203]]

* 周一 [[2022_03_21]] [[Mar 21st, 2022]]
** #今日鸡汤 #周记

如果有人跟你扯什么一个巴掌拍不响，别犹豫，上去就给他一巴掌，这时他肯定立马暴怒。你反问他：我这是怎么拍响的？他肯定继续暴怒：我他妈那是个比喻！我意思是说不要觉得谁都是在莫名其妙别人，被欺负那个人应该先反思自己！这时你可以说：对啊，所以你挨这一巴掌也应该先反思一下自己。

** #今日文章 #周记

《也许你的顿悟，只是别人的基本功》

我曾经在《定位》一书中看过这样一句话，非常的震撼。

原话是这么说的：

任何问题都不是孤立存在的，一定有人曾经遇到过，并且已经有更好的解决办法了，只是我还不知道；我不应该在黑暗中独自前行，也许我的顿悟，只是别人的基本功！我应该站在巨人的肩膀上，学习更成熟的经验和方法，然后再来解决这个问题。

中间有一句话特别扎心”也许你的顿悟，只是别人的基本功”。

所以我现在就特别警惕这件事，做任何事情的时候，我都要停下来，先去找一找这个领域有没有巨人，如果有，先用知识树学一遍，然后再去实操。这也是我之前反复在提的”二元学习法”，很多人都是经验主义者，他们不喜欢学习巨人的知识，只喜欢靠自己的感悟去获得成功。

自己的感悟当然也很重要，但是如果只有自己的感悟，就会出现三大非常大的问题：

第一，你会走很多弯路。因为你每个坑都要趟一遍，甚至趟几遍。
第二，成功的速度比较慢。经验主义者很多是大器晚成，而且他们的成功都是靠经验堆出来的，走了很多弯路。
第三，天花板比较明显。因为成功的边界，就是你认知的边界。

所以，一定要有巨人思维，向有结果的人学习。虽然别人的经验无法完全 100% 复制给你，但是如果你能用 10 个小时的时间，就学到别人辛辛苦苦几十年时间感悟的东西的 50%，那也非常划算了是不是？

大多数人都只是身体上很勤奋，但是思想上很懒惰，他们不懂得站在巨人的肩膀上前行，即使你跟他说，巨人思维很重要，他们依然会觉得”哦，是吗？但是我觉得只有我自己亲身经历的才是自己的。

这，有点傻。


* 周二 [[2022_03_22]] [[Mar 22nd, 2022]]
** #今日鸡汤 #周记

有一辆 70 年的山寨德国车都快散架了，既不肯换发动机，也不肯换刹车。

乘客们还天真的以为只要换个驾驶员就好了。厉害的是这辆破车涂上了一身红漆后竟然准备上高速公路。更要命的是，现在的驾驶员一边开车还一边做梦！最近又开上了逆行车道，还不许乘客打开窗户看外面……


** #今日文章 #周记

《对着干》


社会和教育系统的目的，跟个人的意愿是有冲突的。很多人说要相信学校，相信政策，相信社会，未来会越来越好。这点根本上讲没错，因为政策刺激经济，经济促进社会，社会发展做大蛋糕，最后每个人分到的自然就多了。

但社会和教育系统的目的是让你领蛋糕，而个人奋斗的目的是做那个切蛋糕和抢蛋糕的人。

社会和教育系统自然不可能鼓励所有人都这么做，更不可能传授切蛋糕抢蛋糕的方法。所以按部就班的跟着政策跟着社会跟着学校，最后的结果就是永远只能在时代温饱平均水平线上下挣扎。

对比以往，比如20年前，温饱水平线确实提高了，客观来说你确实变好了，进步了。但这只是纵向，横向来说你其实没什么变化。知识媒体说现在的白领和以前父母时代的工人农民没太大区别，指的就是这么回事。

因此很多人说学校和社会不接轨，不教点真正有用的，学校本来就不能教点有用的。教点有用的，每个人都精明能干，都情商爆表，都游刃有余，毕业了之后都独当一面，快速升职。问题就来了，社会哪有那么多管理类的高薪岗位？

全国的211、985每年毕业人数，起码大几十万快接近100万了，这些人各个都想要高薪想要管理，这咋样都办不到哇。只能用自然筛选机制，即不是教育，而是放马跑，自然筛选。

天赋好的极少数，筛选出来通过竞争，可以独当一面成为管理者。天赋普通的，天赋差的，不教育，不教导，自然发展，毕业了自然成为螺丝钉，底层小卒。整个机制就是这么安排的。

所以你特别在意老师家长的话，积极配合，基本上最后不会有什么好结果。因为你必须明白这个常识：哪怕是天赋好的人，他也不是靠学校教育取胜的，都是靠自学。那天赋普通和天赋较差的，就更要投入千百倍的努力去自学了。


* 周三 [[2022_03_23]] [[Mar 23rd, 2022]]
** #今日鸡汤 #周记

3

** #今日文章 #周记

3


* 周四 [[2022_03_24]] [[Mar 24th, 2022]]
** #今日鸡汤 #周记

4

** #今日文章 #周记

4


* 周五 [[2022_03_25]] [[Mar 25th, 2022]]
** #今日鸡汤 #周记

5

** #今日文章 #周记

5


* 周六 [[2022_03_26]] [[Mar 26th, 2022]]
** #今日鸡汤 #周记

6

** #今日文章 #周记

6


* 周日 [[2022_03_27]] [[Mar 27th, 2022]]
** #今日鸡汤 #周记

7

** #今日文章 #周记

7

